//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planner.Controls.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Note_AddDateToName {
            get {
                return ((bool)(this["Note_AddDateToName"]));
            }
            set {
                this["Note_AddDateToName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Note_AppendDateToNote {
            get {
                return ((bool)(this["Note_AppendDateToNote"]));
            }
            set {
                this["Note_AppendDateToNote"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TimeSheet_SetEndTime {
            get {
                return ((bool)(this["TimeSheet_SetEndTime"]));
            }
            set {
                this["TimeSheet_SetEndTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TimeSheet_SetStartTime {
            get {
                return ((bool)(this["TimeSheet_SetStartTime"]));
            }
            set {
                this["TimeSheet_SetStartTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TimeSheet_ShowJobTime {
            get {
                return ((bool)(this["TimeSheet_ShowJobTime"]));
            }
            set {
                this["TimeSheet_ShowJobTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TimeSheet_OpenQuickAdd {
            get {
                return ((bool)(this["TimeSheet_OpenQuickAdd"]));
            }
            set {
                this["TimeSheet_OpenQuickAdd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Planner_HideOnStartup {
            get {
                return ((bool)(this["Planner_HideOnStartup"]));
            }
            set {
                this["Planner_HideOnStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Planner_CalcTotalTime {
            get {
                return ((bool)(this["Planner_CalcTotalTime"]));
            }
            set {
                this["Planner_CalcTotalTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Planner_MinimizeToSystemTray {
            get {
                return ((bool)(this["Planner_MinimizeToSystemTray"]));
            }
            set {
                this["Planner_MinimizeToSystemTray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TimeSheet_EnableCategories {
            get {
                return ((bool)(this["TimeSheet_EnableCategories"]));
            }
            set {
                this["TimeSheet_EnableCategories"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TimeSheet_EnableTodoItemLink {
            get {
                return ((bool)(this["TimeSheet_EnableTodoItemLink"]));
            }
            set {
                this["TimeSheet_EnableTodoItemLink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TimeSheet_SetTodoCompleteOnEndTime {
            get {
                return ((bool)(this["TimeSheet_SetTodoCompleteOnEndTime"]));
            }
            set {
                this["TimeSheet_SetTodoCompleteOnEndTime"] = value;
            }
        }
    }
}
